{"blogid": "125331752", "writerAge": "码龄15年", "writerBlogNum": "329", "writerCollect": "11396", "writerComment": "7535", "writerFan": "27384", "writerGrade": "8级", "writerIntegral": "34343", "writerName": "dvlinker", "writerProfileAdress": "..\\..\\static\\writer_image\\profile_125331752.jpg", "writerRankTotal": "145", "writerRankWeekly": "5", "writerThumb": "9855", "writerVisitNum": "4620030", "blog_read_count": "1208", "blog_time": "已于 2022-06-18 07:49:44 修改", "blog_title": "VC++异常捕获__try...__except和try...catch的使用介绍（附源码）", "content": "<div class=\"article_content clearfix\" id=\"article_content\">\n<link href=\"../../static/bootstrap/css/csdnstyle.css\" rel=\"stylesheet\"/>\n<div class=\"htmledit_views\" id=\"content_views\">\n<p><a class=\"link-info has-card\" href=\"https://blog.csdn.net/chenlycly/article/details/124272585\" title=\"VC++常用功能开发汇总（专栏文章列表，欢迎订阅，持续更新...）\"><span class=\"link-card-box\"><span class=\"link-title\">VC++常用功能开发汇总（专栏文章列表，欢迎订阅，持续更新...）</span><span class=\"link-link\"><img alt=\"\" class=\"link-link-icon\" src=\"..\\..\\static\\image\\icon-default.png\"/>https://blog.csdn.net/chenlycly/article/details/124272585</span></span></a>       在C/C++的代码中，为了防止代码块执行的过程中产生异常导致软件崩溃，我们会给代码块添加__try...__except或try...catch保护，防止软件因为操作内部触发的异常产生崩溃。本文简单地介绍一下这两种异常捕获的使用示例。</p>\n<h2>1、概述</h2>\n<p>       当软件运行过程中代码抛出异常，如果异常没有处理，且异常不可自动恢复，会导致软件崩溃闪退。C/C++中提供了异常保护机制，可以捕获到异常并处理掉，这样软件不会因为一些操作的内部错误而产生崩溃，软件可以正常的运行下去。</p>\n<p>       C语言中提供了SEH结构化异常捕获<span style=\"color:#be191c;\">__try...__except</span>，C&amp;</p>\n</div>\n</div>", "first_tag": "C++", "cpp": 1, "csharp": 0, "python": 0, "javascript": 0, "java": 0, "sql": 0, "php": 0, "time": "2022-06-18 07:49:44", "summary": "常用功能开发汇总专栏文章列表，欢迎订阅，持续更新常用功能开发汇总专栏文章列表，欢迎订阅，持续更新在的代码中，为了防止代码块执行的过程中产生异常导致软件崩溃，我们会给代码块添加或保护，防止软件因为操作内"}